var WEB3FORMS_KEY='0807768e-222f-4004-9e5a-3e4ed80611b0';
var APPSCRIPT_URL='https://script.google.com/macros/s/AKfycbyI6D28IkKPnoI7z9bh4t9lWMWTy4J0eza6KHc6l1EHa9o3IbspQtJILwynU9alO_z7/exec';
var RD_TOKEN='10b02ef74f4e5da88354848634e7bbeb';
function go(id){ location.href = (id==='home' ? '/' : '/'+id+'/'); }
function goDiag(){ location.href='/diagnostico/#formsec'; }
function scrollToForm(){ var f=document.getElementById('formsec'); if(f) f.scrollIntoView({behavior:'smooth'}); }
function toggleFaq(btn){ var qa=btn.parentElement; qa.classList.toggle('open'); btn.querySelector('.plus').textContent=qa.classList.contains('open')?'–':'+'; }
function animateCount(el){ var target=+el.dataset.count, pre=el.dataset.prefix||'', suf=el.dataset.suffix||'', dur=1400, start=null; function tick(now){ if(!start) start=now; var p=Math.min((now-start)/dur,1), eased=1-Math.pow(1-p,3); el.textContent=pre+Math.round(target*eased)+suf; if(p<1) requestAnimationFrame(tick); } requestAnimationFrame(tick); }
function playStats(){ var band=document.getElementById('statsband'); if(!band) return; var stats=band.querySelectorAll('.stat'); stats.forEach(function(st){ st.classList.remove('in'); var n=st.querySelector('[data-count]'); if(n) n.textContent=(n.dataset.prefix||'')+'0'+(n.dataset.suffix||''); }); stats.forEach(function(st,i){ setTimeout(function(){ st.classList.add('in'); var n=st.querySelector('[data-count]'); if(n) animateCount(n); }, i*150); }); var cred=document.querySelector('.credential'); if(cred){ cred.classList.remove('in'); setTimeout(function(){ cred.classList.add('in'); }, stats.length*150); } }
(function(){ var band=document.getElementById('statsband'); if(!band) return; band.querySelectorAll('[data-count]').forEach(function(n){ n.textContent=(n.dataset.prefix||'')+'0'+(n.dataset.suffix||''); }); var io=new IntersectionObserver(function(entries){ entries.forEach(function(e){ if(e.isIntersecting){ playStats(); io.unobserve(band); } }); },{threshold:.35}); io.observe(band); })();
function submitForm(e){ e.preventDefault(); var wrap=e.target.closest('.form'); var btn=e.target; var payload={access_key:WEB3FORMS_KEY, subject:'Novo cadastro pelo site MARES', from_name:'Site MARES'}; wrap.querySelectorAll('[name]').forEach(function(el){ payload[el.name]=el.value; }); if(!payload['Nome'] || !payload['E-mail']){ alert('Por favor, preencha ao menos nome e e-mail.'); return; } payload.Origem='Site maresconsultoria'; if(APPSCRIPT_URL){ fetch(APPSCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)}).catch(function(){}); } if(RD_TOKEN){ fetch('https://api.rd.services/platform/conversions?api_key='+RD_TOKEN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_type:'CONVERSION',event_family:'CDP',payload:{conversion_identifier:'Cadastro Site MARES',email:payload['E-mail']||'',name:payload['Nome']||'',personal_phone:payload['WhatsApp']||'',company_name:payload['Empresa']||''}})}).catch(function(){}); } var original=btn.textContent; btn.textContent='Enviando...'; btn.disabled=true; fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json();}).then(function(j){ if(j.success){ var okd=wrap.querySelector('.ok'); okd.style.display='block'; btn.style.display='none'; if(window.fbq) fbq('track','Lead'); var nome=(payload['Nome']||'').trim(), emp=(payload['Empresa']||'').trim(), fat=(payload['Faturamento']||'').trim(), msg=(payload['Mensagem']||'').trim(); var txt=(nome?('Olá, sou '+nome+'. '):'Olá! ')+'Acabei de me cadastrar no site da MARES.'; if(emp) txt+=' Empresa: '+emp+'.'; if(fat && fat!=='Selecione') txt+=' Faturamento: '+fat+'.'; if(msg) txt+=' Quero falar sobre: '+msg; var wa=okd.querySelector('a'); if(wa) wa.href='https://wa.me/5541992488092?text='+encodeURIComponent(txt); } else { throw new Error(j.message||'erro'); } }).catch(function(){ btn.textContent=original; btn.disabled=false; alert('Nao consegui enviar agora. Tente de novo ou chame no WhatsApp.'); }); }
